//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFrameWork.CallCenter.Console.CallCenterServiceServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Status", Namespace="http://schemas.datacontract.org/2004/07/TFrameWork.CallCenter.ServiceLib")]
    public enum Status : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotReady = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InUse = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Free = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EmployeeDto", Namespace="http://schemas.datacontract.org/2004/07/TFrameWork.CallCenter.WCF.Service.Dto")]
    [System.SerializableAttribute()]
    public partial class EmployeeDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TFrameWork.CallCenter.Console.CallCenterServiceServiceReference.EmployeeCategory CategoryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LoginField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PriorityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TFrameWork.CallCenter.Console.CallCenterServiceServiceReference.Status StatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TFrameWork.CallCenter.Console.CallCenterServiceServiceReference.EmployeeCategory Category {
            get {
                return this.CategoryField;
            }
            set {
                if ((this.CategoryField.Equals(value) != true)) {
                    this.CategoryField = value;
                    this.RaisePropertyChanged("Category");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Login {
            get {
                return this.LoginField;
            }
            set {
                if ((object.ReferenceEquals(this.LoginField, value) != true)) {
                    this.LoginField = value;
                    this.RaisePropertyChanged("Login");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Priority {
            get {
                return this.PriorityField;
            }
            set {
                if ((this.PriorityField.Equals(value) != true)) {
                    this.PriorityField = value;
                    this.RaisePropertyChanged("Priority");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TFrameWork.CallCenter.Console.CallCenterServiceServiceReference.Status Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EmployeeCategory", Namespace="http://schemas.datacontract.org/2004/07/TFrameWork.CallCenter.ServiceLib")]
    public enum EmployeeCategory : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Operator = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Manager = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Director = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CallCenterServiceServiceReference.ICallCenterService")]
    public interface ICallCenterService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICallCenterService/Login", ReplyAction="http://tempuri.org/ICallCenterService/LoginResponse")]
        void Login([System.ServiceModel.MessageParameterAttribute(Name="login")] string login1);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICallCenterService/Login", ReplyAction="http://tempuri.org/ICallCenterService/LoginResponse")]
        System.Threading.Tasks.Task LoginAsync(string login);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICallCenterService/UpdateState", ReplyAction="http://tempuri.org/ICallCenterService/UpdateStateResponse")]
        void UpdateState(string login, TFrameWork.CallCenter.Console.CallCenterServiceServiceReference.Status status);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICallCenterService/UpdateState", ReplyAction="http://tempuri.org/ICallCenterService/UpdateStateResponse")]
        System.Threading.Tasks.Task UpdateStateAsync(string login, TFrameWork.CallCenter.Console.CallCenterServiceServiceReference.Status status);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICallCenterService/GetFreeEmloyee", ReplyAction="http://tempuri.org/ICallCenterService/GetFreeEmloyeeResponse")]
        TFrameWork.CallCenter.Console.CallCenterServiceServiceReference.EmployeeDto GetFreeEmloyee();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICallCenterService/GetFreeEmloyee", ReplyAction="http://tempuri.org/ICallCenterService/GetFreeEmloyeeResponse")]
        System.Threading.Tasks.Task<TFrameWork.CallCenter.Console.CallCenterServiceServiceReference.EmployeeDto> GetFreeEmloyeeAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICallCenterService/GetEmployes", ReplyAction="http://tempuri.org/ICallCenterService/GetEmployesResponse")]
        TFrameWork.CallCenter.Console.CallCenterServiceServiceReference.EmployeeDto[] GetEmployes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICallCenterService/GetEmployes", ReplyAction="http://tempuri.org/ICallCenterService/GetEmployesResponse")]
        System.Threading.Tasks.Task<TFrameWork.CallCenter.Console.CallCenterServiceServiceReference.EmployeeDto[]> GetEmployesAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICallCenterServiceChannel : TFrameWork.CallCenter.Console.CallCenterServiceServiceReference.ICallCenterService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CallCenterServiceClient : System.ServiceModel.ClientBase<TFrameWork.CallCenter.Console.CallCenterServiceServiceReference.ICallCenterService>, TFrameWork.CallCenter.Console.CallCenterServiceServiceReference.ICallCenterService {
        
        public CallCenterServiceClient() {
        }
        
        public CallCenterServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CallCenterServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CallCenterServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CallCenterServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void Login(string login1) {
            base.Channel.Login(login1);
        }
        
        public System.Threading.Tasks.Task LoginAsync(string login) {
            return base.Channel.LoginAsync(login);
        }
        
        public void UpdateState(string login, TFrameWork.CallCenter.Console.CallCenterServiceServiceReference.Status status) {
            base.Channel.UpdateState(login, status);
        }
        
        public System.Threading.Tasks.Task UpdateStateAsync(string login, TFrameWork.CallCenter.Console.CallCenterServiceServiceReference.Status status) {
            return base.Channel.UpdateStateAsync(login, status);
        }
        
        public TFrameWork.CallCenter.Console.CallCenterServiceServiceReference.EmployeeDto GetFreeEmloyee() {
            return base.Channel.GetFreeEmloyee();
        }
        
        public System.Threading.Tasks.Task<TFrameWork.CallCenter.Console.CallCenterServiceServiceReference.EmployeeDto> GetFreeEmloyeeAsync() {
            return base.Channel.GetFreeEmloyeeAsync();
        }
        
        public TFrameWork.CallCenter.Console.CallCenterServiceServiceReference.EmployeeDto[] GetEmployes() {
            return base.Channel.GetEmployes();
        }
        
        public System.Threading.Tasks.Task<TFrameWork.CallCenter.Console.CallCenterServiceServiceReference.EmployeeDto[]> GetEmployesAsync() {
            return base.Channel.GetEmployesAsync();
        }
    }
}
